### ISSUE TITLE
after entering in password of railo administrator I am prompted again

### ISSUE THREAD

**Issue by randy-johnson** [misterdai/cftracker#29]
after entering in password of railo administrator I am prompted again to enter the password.  I enter the password and it just refreshes the page.    This is a new install on the latest version of railo

chrome dev tools show post to action=login.login.  Then  action=main.default  then action=login.login and then action=login.default.

Any ideas what is going on here?  I have tried in Chrome and Firefox.

Randy

**Comment by sebgmc** [comment]
This does not occur on any Railo 4.x installations I have checked.
