### ISSUE TITLE
Sessions page error on Railo: No matching Method/Function for getAllSessionScopes

### ISSUE THREAD

**Issue by oyovadaniel** [misterdai/cftracker#50]
Full stack trace:

No matching Method/Function for railo.runtime.type.scope.ScopeContext.getAllSessionScopes(railo.runtime.config.ConfigWebImpl, string) found at railo.runtime.reflection.Reflector.throwCall(Reflector.java:715):715 at railo.runtime.reflection.Reflector.callMethod(Reflector.java:696):696 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:742):742 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1480):1480 at cftracker.services.cftracker.sessions_cfc$cf._1(/home/test/public_html/apps/cftracker/services/cftracker/sessions.cfc:87):87 at cftracker.services.cftracker.sessions_cfc$cf.udfCall(/home/test/public_html/apps/cftracker/services/cftracker/sessions.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:215):215 at railo.runtime.type.UDFImpl._call(UDFImpl.java:434):434 at railo.runtime.type.UDFImpl.call(UDFImpl.java:384):384 at railo.runtime.ComponentScopeShadow.call(ComponentScopeShadow.java:317):317 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:733):733 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1480):1480 at cftracker.services.cftracker.sessions_cfc$cf._2(/home/test/public_html/apps/cftracker/services/cftracker/sessions.cfc:328):328 at cftracker.services.cftracker.sessions_cfc$cf.udfCall(/home/test/public_html/apps/cftracker/services/cftracker/sessions.cfc):-1

Context: 
/home/test/public_html/apps/cftracker/services/cftracker/sessions.cfc 

85: lc.temp = lc.scopeContext.getAllSessionScopes(getPageContext(), lc.app); 
86: } else { 
87: lc.temp = lc.scopeContext.getAllSessionScopes(lc.configs[lc.c], lc.app); 
88: } 
89: lc.keys = StructKeyArray(lc.temp);

**Comment by sebgmc** [comment]
Hi, I know this is discontinued, but still would like to chime in that the suggested fix did not work. I get this stacktrace when changing the above on Railo 4.2.1.008 (stable):

No matching Method/Function for railo.runtime.type.scope.ScopeContext.getAllSessionScopes(railo.runtime.config.ConfigWebImpl, string) found at railo.runtime.reflection.Reflector.throwCall(Reflector.java:906):906 at railo.runtime.reflection.Reflector.callMethod(Reflector.java:837):837 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:738):738 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547 at cftracker.services.cftracker.sessions_cfc$cf.udfCall1(/var/www/cftracker/services/cftracker/sessions.cfc:101):101 at cftracker.services.cftracker.sessions_cfc$cf.udfCall(/var/www/cftracker/services/cftracker/sessions.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93 at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307 at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208 at railo.runtime.ComponentScopeShadow.call(ComponentScopeShadow.java:270):270 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547 at cftracker.services.cftracker.sessions_cfc$cf.udfCall2(/var/www/cftracker/services/cftracker/sessions.cfc:390):390 at cftracker.services.cftracker.sessions_cfc$cf.udfCall(/var/www/cftracker/services/cftracker/sessions.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93 at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307 at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208 at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623 at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547 at cftracker.services.sessions_cfc$cf.udfCall(/var/www/cftracker/services/sessions.cfc:14):14 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93 at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307 at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195 at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624 at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506 at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1751):1751 at railo.runtime.tag.Invoke.doComponent(Invoke.java:203):203 at railo.runtime.tag.Invoke.doEndTag(Invoke.java:176):176 at cftracker.framework_cfc$cf.udfCall6(/var/www/cftracker/framework.cfc:1273):1273 at cftracker.framework_cfc$cf.udfCall(/var/www/cftracker/framework.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93 at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307 at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208 at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:748):748 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547 at cftracker.framework_cfc$cf.udfCall2(/var/www/cftracker/framework.cfc:491):491 at cftracker.framework_cfc$cf.udfCall(/var/www/cftracker/framework.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93 at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307 at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208 at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623 at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738 at railo.runtime.listener.ModernAppListener.call(ModernAppListener.java:388):388 at railo.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:204):204 at railo.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:18):18 at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2212):2212 at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2179):2179 at railo.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:331):331 at railo.loader.servlet.CFMLServlet.service(CFMLServlet.java:29):29 at javax.servlet.http.HttpServlet.service(HttpServlet.java:722):722 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305):305 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210):210 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224):224 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169):169 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472):472 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168):168 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98):98 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118):118 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407):407 at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200):200 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579):579 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307):307 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615 at java.lang.Thread.run(Thread.java:745):745 

Context:
99: lc.temp = lc.scopeContext.getAllSessionScopes(getPageContext(), lc.app);
100: } else {
101: lc.temp = lc.scopeContext.getAllSessionScopes(lc.app);
102: }
103: lc.keys = StructKeyArray(lc.temp);
